export const SORT_ASCENDING = 'SORT_ASCENDING';
export const SORT_DESCENDING = 'SORT_DEASCENDING';
export const FETCH_PROFILES_BEGINS = 'FETCH_PROFILES_BEGINS';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';
export const FETCH_PROFILE = 'FETCH_PROFILE';
